name: CI-compile

on:
  push:
  pull_request:

jobs:
  build:
    name: wnbd compilation
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build
        run: |
          cd PS2IDBMS
          msbuild wnbd\vstudio\wnbd.sln
