name: CI-compile

on:
  push:
  pull_request:

jobs:
  build:
    name: wnbd compilation
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - run: git fetch --prune --unshallow

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build
        run: |
          cd vstudio
          msbuild wnbd.sln /p:Configuration=Release
          mkdir Release
          copy x64/Release/wnbd-client.exe Release/
          copy x64/Release/driver/**/* Release/
          copy x64/Release/libwnbd.dll Release/
          copy ../reinstall.ps1 Release/
          copy wnbdevents.xml Release/
          
      - uses: actions/upload-artifact@v2
        with:
          name: WNBD
          path: vstudio/Release/            
